### ISSUE TITLE
Make the title optional

### ISSUE THREAD

**Issue by kevin-larry-bauer** [byuweb/calendar-widget#3]
I want to use this widget on a section of my page that already has an H1 title for that section, but the widget adds an h2 automatically, even when I don't specify a title. If I put in a blank title the result is a huge space:

![image](https://user-images.githubusercontent.com/19493582/27807770-36cf4976-6000-11e7-84c3-d42e63ff310a.png)

**Comment by rburkey87** [comment]
@kebowdog - we've added the class "calendar-block-title" to the header so you can reference that with a `display: none` if you'd prefer to disable the header.

**Comment by kevin-larry-bauer** [comment]
Cool, I'll go that route for now.

**Comment by rburkey87** [comment]
@kebowdog - can you close this issue? I don't have write access

**Comment by kevin-larry-bauer** [comment]
Done.
